# Site settings
title: Insert Personal Brand Here
recaptcha-email: "http://www.google.com/recaptcha/mailhide/d?k=01o_olz5aDTT72o-t3H0hnRA==&c=a2CWfPNW3-gP0i48dUlwKtUw_mvCZ1P1KvMO6jFxR1s="
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jra3.github.io" # the base hostname & protocol for your site
twitter_username: porcnick
github_username:  jra3

# Build settings
markdown: kramdown
